#!/usr/bin/env bash

function run  {
      if ! pgrep -f $1 ;
            then
                    $@&
                      fi
  }

$HOME/.config/bspwm/utilities/setbg
flock -n $HOME/.local/bin/lock $HOME/.local/bin/gamemodeloop &
dunst &
volnoti &
